gf1LastReadIndex: 3
gf2LastReadIndex: 0
instanceName: instance294124
link: drivekraft
mainSheetName: Dev Session Record CRM version
qualitySheet: Session Feedback Form (Responses)
timingSheet: Psychologist Timings
